layout_spectrum: 0.2741936
color:
  saturation: 0.9426523
  brandStrength: 0.09666389
  lightness: 0.04121864
  rhythmicContrast: 0.4899784
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.5322581
name: KickRocks
